server:
  port: 7050
spring:
  application:
    name: recommendation-service
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

say-Hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8060,localhost:8061
    ServerListRefreshInterval: 15000
